/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/assets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 上传一张作业或试卷图片 */
        post: operations["upload_asset_api_v1_assets_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取来源图片元数据 */
        get: operations["get_asset_api_v1_assets__asset_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/content": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取来源图片内容 */
        get: operations["get_asset_content_api_v1_assets__asset_id__content_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/detection-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 可选：自动检测题目候选框 */
        post: operations["create_detection_run_api_v1_assets__asset_id__detection_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/problems": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取这张来源页中的全部错题 */
        get: operations["list_asset_problems_api_v1_assets__asset_id__problems_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/regions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 保存一个人工题目框 */
        post: operations["create_region_api_v1_assets__asset_id__regions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/assets/{asset_id}/regions/batch": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 批量保存教师确认的题目框 */
        post: operations["create_regions_batch_api_v1_assets__asset_id__regions_batch_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 检查系统与 Provider 状态 */
        get: operations["health_api_v1_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{problem_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取一条完整的规范化题目记录 */
        get: operations["get_problem_api_v1_problems__problem_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/problems/{problem_id}/publications/lark": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 把已整理题目发布到飞书 Base */
        post: operations["publish_problem_api_v1_problems__problem_id__publications_lark_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/{region_id}/crop": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 读取题目裁图 */
        get: operations["get_region_crop_api_v1_regions__region_id__crop_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/{region_id}/ocr-runs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 新增一次 OCR 识别 */
        post: operations["create_ocr_run_api_v1_regions__region_id__ocr_runs_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/regions/{region_id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 保存一个新的教师修订版本 */
        post: operations["create_revision_api_v1_regions__region_id__revisions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AssetProblemCollectionResponse */
        AssetProblemCollectionResponse: {
            /** Assetid */
            assetId: string;
            /** Count */
            count: number;
            /** Items */
            items: components["schemas"]["NormalizedProblemResponse"][];
        };
        /** BatchRegionCreateRequest */
        BatchRegionCreateRequest: {
            /**
             * Coordinatesystem
             * @constant
             */
            coordinateSystem: "normalized_top_left";
            /** Regions */
            regions: components["schemas"]["RegionSelectionRequest"][];
        };
        /** BatchRegionCreateResponse */
        BatchRegionCreateResponse: {
            /** Createdcount */
            createdCount: number;
            /** Items */
            items: components["schemas"]["RegionCreateResponse"][];
        };
        /** Body_upload_asset_api_v1_assets_post */
        Body_upload_asset_api_v1_assets_post: {
            /**
             * File
             * @description JPG、JPEG 或 PNG 图片
             */
            file: string;
        };
        /** ErrorBody */
        ErrorBody: {
            /** Code */
            code: string;
            /** Details */
            details: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Message */
            message: string;
            /** Requestid */
            requestId: string;
            /** Retryable */
            retryable: boolean;
        };
        /** ErrorEnvelope */
        ErrorEnvelope: {
            error: components["schemas"]["ErrorBody"];
        };
        /** HealthResponse */
        HealthResponse: {
            /**
             * Database
             * @constant
             */
            database: "ok";
            /** Ocrprovider */
            ocrProvider: string;
            /** Regiondetectionprovider */
            regionDetectionProvider: string;
            /**
             * Status
             * @constant
             */
            status: "ok";
        };
        /** HistoryResponse */
        HistoryResponse: {
            /** Ocrruns */
            ocrRuns: components["schemas"]["OCRRunResponse"][];
            /** Revisions */
            revisions: components["schemas"]["ProblemRevisionResponse"][];
        };
        JsonValue: unknown;
        /** LineageResponse */
        LineageResponse: {
            /** Detectioncandidateid */
            detectionCandidateId: string | null;
            /** Detectioncandidateids */
            detectionCandidateIds: string[];
            /** Ocrrunid */
            ocrRunId: string | null;
            /** Problemregionid */
            problemRegionId: string;
            /** Revisionid */
            revisionId: string | null;
            /** Sourceassetid */
            sourceAssetId: string;
        };
        /** NormalizedBBoxRequest */
        NormalizedBBoxRequest: {
            /** Height */
            height: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** NormalizedBBoxResponse */
        NormalizedBBoxResponse: {
            /** Height */
            height: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** NormalizedProblemResponse */
        NormalizedProblemResponse: {
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            history: components["schemas"]["HistoryResponse"];
            humanRevision: components["schemas"]["ProblemRevisionResponse"] | null;
            latestOcrRun: components["schemas"]["OCRRunResponse"] | null;
            lineage: components["schemas"]["LineageResponse"];
            ocr: components["schemas"]["OCRRunResponse"] | null;
            /** Problemid */
            problemId: string;
            publication: components["schemas"]["ProblemPublicationResponse"] | null;
            region: components["schemas"]["ProblemRegionResponse"];
            source: components["schemas"]["SourceAssetResponse"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** OCRBlockResponse */
        OCRBlockResponse: {
            bbox: components["schemas"]["PixelBBoxResponse"] | null;
            /** Confidence */
            confidence: number | null;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            /** Readingorder */
            readingOrder: number;
            /** Text */
            text: string;
            type: components["schemas"]["OCRBlockType"];
        };
        /**
         * OCRBlockType
         * @enum {string}
         */
        OCRBlockType: "text" | "formula" | "table" | "diagram" | "unknown";
        /** OCRRunResponse */
        OCRRunResponse: {
            /** Blocks */
            blocks: components["schemas"]["OCRBlockResponse"][];
            /** Confidence */
            confidence: number | null;
            /** Errorcode */
            errorCode: string | null;
            /** Finishedat */
            finishedAt: string | null;
            /** Model */
            model: string | null;
            /** Processingtimems */
            processingTimeMs: number | null;
            /** Provider */
            provider: string;
            /** Providerversion */
            providerVersion: string | null;
            rawResponse: components["schemas"]["JsonValue"] | null;
            /** Runid */
            runId: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            status: components["schemas"]["OCRRunStatus"];
            /** Text */
            text: string | null;
            /** Warnings */
            warnings: string[];
        };
        /**
         * OCRRunStatus
         * @enum {string}
         */
        OCRRunStatus: "running" | "succeeded" | "failed";
        /** PixelBBoxResponse */
        PixelBBoxResponse: {
            /** Height */
            height: number;
            /** Width */
            width: number;
            /** X */
            x: number;
            /** Y */
            y: number;
        };
        /** ProblemPublicationResponse */
        ProblemPublicationResponse: {
            /** Basename */
            baseName: string;
            /** Errorcode */
            errorCode: string | null;
            /** Finishedat */
            finishedAt: string | null;
            /** Pagerecordid */
            pageRecordId: string | null;
            /** Pagestableid */
            pagesTableId: string | null;
            /** Publicationid */
            publicationId: string;
            /** Publishedrevisionid */
            publishedRevisionId: string;
            /** Publisher */
            publisher: string;
            /** Questionrecordid */
            questionRecordId: string | null;
            /** Questionstableid */
            questionsTableId: string | null;
            /** Retryable */
            retryable: boolean;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            status: components["schemas"]["PublicationStatus"];
            /**
             * Updatedat
             * Format: date-time
             */
            updatedAt: string;
        };
        /** ProblemRegionResponse */
        ProblemRegionResponse: {
            bbox: components["schemas"]["PixelBBoxResponse"];
            /** Coordinatesystem */
            coordinateSystem: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Cropcontenturl */
            cropContentUrl: string;
            /** Croppedassetkey */
            croppedAssetKey: string;
            /** Detectioncandidateid */
            detectionCandidateId: string | null;
            /** Detectioncandidateids */
            detectionCandidateIds: string[];
            /** Pagenumber */
            pageNumber: number;
            /** Regionid */
            regionId: string;
            selectionSource: components["schemas"]["RegionSelectionSource"];
        };
        /** ProblemRevisionResponse */
        ProblemRevisionResponse: {
            /** Basedonocrrunid */
            basedOnOcrRunId: string;
            /** Correctedtext */
            correctedText: string;
            /** Correctionnote */
            correctionNote: string | null;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Revisionid */
            revisionId: string;
            /** Revisionnumber */
            revisionNumber: number;
        };
        /**
         * PublicationStatus
         * @enum {string}
         */
        PublicationStatus: "pending" | "succeeded" | "failed";
        /** RegionCandidateResponse */
        RegionCandidateResponse: {
            bbox: components["schemas"]["PixelBBoxResponse"];
            /** Confidence */
            confidence: number | null;
            /** Coordinatesystem */
            coordinateSystem: string;
            /** Detectioncandidateid */
            detectionCandidateId: string;
            /** Metadata */
            metadata: {
                [key: string]: components["schemas"]["JsonValue"];
            };
            normalizedBbox: components["schemas"]["NormalizedBBoxResponse"];
            /** Providercandidateid */
            providerCandidateId: string;
            /** Readingorder */
            readingOrder: number;
        };
        /** RegionCreateRequest */
        RegionCreateRequest: {
            bbox: components["schemas"]["NormalizedBBoxRequest"];
            /**
             * Coordinatesystem
             * @constant
             */
            coordinateSystem: "normalized_top_left";
        };
        /** RegionCreateResponse */
        RegionCreateResponse: {
            bbox: components["schemas"]["PixelBBoxResponse"];
            /** Coordinatesystem */
            coordinateSystem: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Cropcontenturl */
            cropContentUrl: string;
            /** Detectioncandidateid */
            detectionCandidateId: string | null;
            /** Detectioncandidateids */
            detectionCandidateIds: string[];
            /** Problemid */
            problemId: string;
            /** Regionid */
            regionId: string;
            selectionSource: components["schemas"]["RegionSelectionSource"];
        };
        /** RegionDetectionRunResponse */
        RegionDetectionRunResponse: {
            /** Candidates */
            candidates: components["schemas"]["RegionCandidateResponse"][];
            /** Errorcode */
            errorCode: string | null;
            /**
             * Finishedat
             * Format: date-time
             */
            finishedAt: string;
            /** Model */
            model: string | null;
            /** Processingtimems */
            processingTimeMs: number;
            /** Provider */
            provider: string;
            /** Providerversion */
            providerVersion: string | null;
            /** Runid */
            runId: string;
            /**
             * Startedat
             * Format: date-time
             */
            startedAt: string;
            status: components["schemas"]["RegionDetectionRunStatus"];
            /** Warnings */
            warnings: string[];
        };
        /**
         * RegionDetectionRunStatus
         * @enum {string}
         */
        RegionDetectionRunStatus: "succeeded" | "failed";
        /** RegionSelectionRequest */
        RegionSelectionRequest: {
            bbox: components["schemas"]["NormalizedBBoxRequest"];
            /** Detectioncandidateids */
            detectionCandidateIds?: string[];
            selectionSource: components["schemas"]["RegionSelectionSource"];
        };
        /**
         * RegionSelectionSource
         * @enum {string}
         */
        RegionSelectionSource: "manual" | "detected";
        /** RevisionCreateRequest */
        RevisionCreateRequest: {
            /** Basedonocrrunid */
            basedOnOcrRunId: string;
            /** Correctedtext */
            correctedText: string;
            /** Correctionnote */
            correctionNote?: string | null;
        };
        /** SourceAssetResponse */
        SourceAssetResponse: {
            /** Assetid */
            assetId: string;
            /** Contenturl */
            contentUrl: string;
            /**
             * Createdat
             * Format: date-time
             */
            createdAt: string;
            /** Duplicateofassetid */
            duplicateOfAssetId?: string | null;
            /** Filehash */
            fileHash: string;
            /** Filename */
            fileName: string;
            /** Filesize */
            fileSize: number;
            /** Height */
            height: number;
            /** Mediatype */
            mediaType: string;
            /** Storagekey */
            storageKey: string;
            /** Width */
            width: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    upload_asset_api_v1_assets_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": components["schemas"]["Body_upload_asset_api_v1_assets_post"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAssetResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 上传图片超过系统允许的大小。 */
            413: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 上传文件不是支持的图片格式。 */
            415: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_asset_api_v1_assets__asset_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceAssetResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_asset_content_api_v1_assets__asset_id__content_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_detection_run_api_v1_assets__asset_id__detection_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionDetectionRunResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 外部识别服务返回了无法解析的结果。 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 识别或发布服务暂时不可用，或尚未正确配置。 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 外部识别服务运行超时。 */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    list_asset_problems_api_v1_assets__asset_id__problems_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssetProblemCollectionResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_region_api_v1_assets__asset_id__regions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RegionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RegionCreateResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_regions_batch_api_v1_assets__asset_id__regions_batch_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                asset_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["BatchRegionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BatchRegionCreateResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 当前状态不允许执行这个操作。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    health_api_v1_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_problem_api_v1_problems__problem_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NormalizedProblemResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    publish_problem_api_v1_problems__problem_id__publications_lark_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                problem_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemPublicationResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 当前状态不允许执行这个操作。 */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 外部识别服务返回了无法解析的结果。 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 识别或发布服务暂时不可用，或尚未正确配置。 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 外部识别服务运行超时。 */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    get_region_crop_api_v1_regions__region_id__crop_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_ocr_run_api_v1_regions__region_id__ocr_runs_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OCRRunResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 外部识别服务返回了无法解析的结果。 */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 识别或发布服务暂时不可用，或尚未正确配置。 */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 外部识别服务运行超时。 */
            504: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
    create_revision_api_v1_regions__region_id__revisions_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                region_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RevisionCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProblemRevisionResponse"];
                };
            };
            /** @description HTTP 请求或上传表单格式错误。 */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 找不到请求的来源材料或题目记录。 */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 请求内容没有通过校验。 */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
            /** @description 系统内部或本地文件存储发生错误。 */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorEnvelope"];
                };
            };
        };
    };
}
